int=int(input("Enter a number:"))
char=input("Enter a character:")
float=float(input("Enter a float:"))
bool=(input("Enter a boolean:"))
complex=(input("Enter a complex:"))
list=(input("Enter a list:"))
array=(input("Enter a array:"))
tuple=(input("Enter a tuple:"))
dict=(input("Enter a dictionary:"))
set=(input("Enter a set:"))
print(type(int),int)
print(type(char),char)
print(type(float),float)
print(type(bool),bool)
print(type(complex),complex)
print(type(list),list)
print(type(array),array)
print(type(tuple),tuple)
print(type(dict),dict)
print(type(set),set)
